### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [D1W0U/Arduino-HMC5983#1]
In the file "HMC5983.cpp" the Wire.requestFrom() is followed by Wire.endTransmission() in three places. You can remove those Wire.endTransmission().

The Wire.endTransmission() is only used when writing data.

**Comment by D1W0U** [comment]
Okay, I'm on it! Thanks for your contribution!

**Comment by D1W0U** [comment]
fixed!

**Comment by Koepel** [comment]
I took a better look at your code, and there are few more things.

In two places there is a Wire.beginTransmission() before the Wire.requestFrom(). You can remove those Wire.beginTransmission() as well. Just like the Wire.endTransmission, it is only used when writing data.

There is no need to wait for something after calling Wire.requestFrom(). You can remove the two lines with `while(!Wire.available()) {};`.

At the end a Wire.requestFrom() is done to request three bytes to point to the first data registers. Is that correct ? I would expect a combination of: Wire.beginTransmission() - Wire.write() - Wire.endTransmission().

**Comment by D1W0U** [comment]
Thanks for your contribution.

Do you think that would be a good approach for the pointing to the first data registers?

```
  // point to first data register (from datasheet). Only for continuous-measurement mode.
  Wire.beginTransmission(HMC5983_ADDRESS);
  #if ARDUINO >= 100
      Wire.write(0x03);
  #else
      Wire.send(0x03);
  #endif
  Wire.endTransmission();
```

**Comment by Koepel** [comment]
I think you don't need that at all.
In the example "HMC5983_UltrafastCompass.ino", the flag is tested, and compass.read() is called. In the function HMC5983::read() the registers are read with readRegister8(), that function sets the address pointer (register location inside the sensor) and reads the data. That is the normal way to do it. There is no need to set the address pointer again at the end of that function.

A few tips:
- The Wire.send() and Wire.receive() are very old. There is probably no need to be compatible with such old functions.
- You can speed up things, by requesting all 6 bytes for X,Y,Z with a single Wire.requestFrom(). I mean writing the address pointer followed by a `Wire.requestFrom(HMC5983_ADDRESS, 6)`.
- You can also speed up things by using `Wire.setClock(400000L);` for 400kHz. For 400kHz and a 5V Arduino board you might need a I2C level shifter.

**Comment by D1W0U** [comment]
Thanks for your contribution.

I'm buying a new device to test those that changes before commit them, as mine was burnt by a bad wiring, some time ago.

I'm giving you an answer when finished.

**Comment by SigP226** [comment]
Hi,

here is the modification for the pointer and reading the 6 register

double HMC5983::read() {
  // the values for X, Y & Z must be read in X, Z & Y order.
  writeRegister8(HMC5983_OUT_X_MSB,0); // Select MSB X register
  Wire.requestFrom(HMC5983_ADDRESS, 6);
  byte X_MSB = Wire.read();
  byte X_LSB = Wire.read();
  byte Z_MSB = Wire.read();
  byte Z_LSB = Wire.read();
  byte Y_MSB = Wire.read();
  byte Y_LSB = Wire.read();

**Comment by D1W0U** [comment]
Thanks, it's modified.

**Comment by IvanKor** [comment]
> here is the modification for the pointer and reading the 6 register

this does not work

**Comment by IvanKor** [comment]
> here is the modification for the pointer and reading the 6 register

  Wire.beginTransmission(HMC5983_ADDRESS);
  Wire.write(HMC5983_REG_OUT_X_M);
  Wire.endTransmission();
  Wire.beginTransmission(HMC5983_ADDRESS);  
  Wire.requestFrom(HMC5983_ADDRESS, 6);
  while(!Wire.available()) {};
  byte X_MSB = Wire.read();
  byte X_LSB = Wire.read();
  byte Z_MSB = Wire.read();
  byte Z_LSB = Wire.read();
  byte Y_MSB = Wire.read();
  byte Y_LSB = Wire.read();
  Wire.endTransmission();

**Comment by Koepel** [comment]
IvanKor, the `while(!Wire.available()) {};` is not okay, and the Wire.beginTransmission() and Wire.endTransmission() should not be used together with Wire.requestFrom(). I wrote a wiki to explain it: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes)

D1W0U, there are still a few problems with the code. The same common mistakes that I just mentioned are also in the library and the Wire.requestFrom() at the very bottom to point to a register it not normal.

**Comment by D1W0U** [comment]
Please, submit pull requests. I am not actually developing this library. Thanks in advance and sorry.

**Comment by IvanKor** [comment]
@Koepel 
however this code works
whereas the @SigP226 code produces a noise

Naturally, you can reduce:

Wire.beginTransmission(HMC5983_ADDRESS);
Wire.write(HMC5983_REG_OUT_X_M);
Wire.requestFrom(HMC5983_ADDRESS, 6);
byte X_MSB = Wire.read();
byte X_LSB = Wire.read();
byte Z_MSB = Wire.read();
byte Z_LSB = Wire.read();
byte Y_MSB = Wire.read();
byte Y_LSB = Wire.read();
Wire.endTransmission();

However, I'm not sure that this is correct

**Comment by Koepel** [comment]
@IvanKor that code is not correct. Could read this [Explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library) and this [Common mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes).

I have not even made a "common mistake" for mixing writing and reading.

If the @SigP226 code is causing noise, then perhaps something else is wrong. I have a HMC5983, but I'm not able to test it right now.
